"""Compatibility shim — implementation lives in resources.lib.meta.provider_settings."""
from resources.lib.meta.provider_settings import (  # noqa: F401
    ART_FANART,
    ART_SIMKL,
    ART_TMDB,
    ART_TVDB,
    MDBLIST_DISCOVER_DB_QUERIES,
    _API_NAME_BY_PROVIDER,
    advanced_artwork_enabled,
    art_gapfill_available,
    art_limit,
    art_option_enabled,
    art_provider_usable,
    cast_gapfill_available,
    discover_db_query_allowed,
    discover_list_visible,
    effective_preferred_art_source,
    external_ids_from_row,
    fanart_art_usable,
    filter_discover_lists,
    gapfill_provider_available_for_row,
    gapfill_providers_enabled,
    mdblist_runtime_enabled,
    notify_tmdb_required,
    provider_enabled,
)
